version: "3.9"
services:
  bee:
    environment:
      - BEE_ADMIN_BASE_API=http://47.242.89.189:5000
      - BEE_MACHINE_GROUP=SG
      - BEE_API_SECURE_KEY=123
    image: "kkwang/bee-node-multi:0.6.2"
    volumes:
      - "./data/bee:/opt/data"
      - "/etc/hostname:/opt/hostname"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1